# Generated by Django 3.2.13 on 2022-06-25 10:03

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_personalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='district',
            field=models.CharField(default=sqlalchemy.sql.expression.false, max_length=50),
        ),
    ]
