# Generated by Django 3.2.13 on 2022-06-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_personalinfo_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='district',
            new_name='District',
        ),
    ]
