# Generated by Django 3.2.13 on 2022-06-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_district_personalinfo_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Administration',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
