# Generated by Django 3.2.13 on 2022-06-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_personalinfo_administration'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Office',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Administration',
            field=models.CharField(max_length=50),
        ),
    ]
