# Generated by Django 3.2.13 on 2022-06-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20220625_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='Office',
            field=models.CharField(max_length=50),
        ),
    ]
