# Generated by Django 3.2.13 on 2022-06-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_personalinfo_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Ministry',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
