# Generated by Django 3.2.13 on 2022-06-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_personalinfo_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Atonomous',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
