# Generated by Django 3.0.14 on 2022-06-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20220625_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Disability',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
