# Generated by Django 3.0.14 on 2022-06-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_personalinfo_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='Family',
        ),
    ]
