# Generated by Django 3.0.14 on 2022-06-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_personalinfo_mothername'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Telephone',
            field=models.IntegerField(default=False, max_length=50),
        ),
    ]
