# Generated by Django 3.0.14 on 2022-06-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20220626_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='Telephone',
            field=models.CharField(default=False, max_length=12),
        ),
    ]
