# Generated by Django 3.0.14 on 2022-06-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20220626_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Date',
            field=models.DateField(default=False),
        ),
    ]
