# Generated by Django 3.0.14 on 2022-06-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_personalinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='Date',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
