# Generated by Django 3.0.14 on 2022-06-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20220626_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='Date',
            new_name='Dateee',
        ),
    ]
