# Generated by Django 3.0.14 on 2022-06-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20220626_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='Dateee',
            new_name='Birth',
        ),
    ]
