# Generated by Django 3.0.14 on 2022-06-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20220626_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='Birth',
        ),
    ]
