# Generated by Django 3.0.14 on 2022-06-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_personalinfo_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Fourth',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
