# Generated by Django 3.0.14 on 2022-06-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_personalinfo_fourth'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Tell',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
