# Generated by Django 3.0.14 on 2022-06-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_personalinfo_tell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='Tell',
        ),
    ]
