# Generated by Django 3.0.14 on 2022-06-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_personalinfo_tell'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Frname',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
