# Generated by Django 3.0.14 on 2022-06-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_personalinfo_frname'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalinfo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fulladress', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Administration', models.CharField(max_length=50)),
                ('Office', models.CharField(max_length=50)),
                ('Ministry', models.CharField(default=False, max_length=50)),
                ('Area', models.CharField(default=False, max_length=50)),
                ('Atonomous', models.CharField(default=False, max_length=50)),
                ('Disability', models.CharField(default=False, max_length=50)),
                ('Apartment', models.CharField(default=False, max_length=50)),
                ('Family', models.CharField(default=False, max_length=50)),
                ('Mothername', models.CharField(default=False, max_length=50)),
                ('Telephone', models.CharField(default=False, max_length=12)),
                ('Frname', models.CharField(default=False, max_length=50)),
            ],
        ),
    ]
