# Generated by Django 3.0.14 on 2022-06-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_personalinfo1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='personalinfo1',
        ),
    ]
