# Generated by Django 3.0.14 on 2022-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_personalinfo_teleph'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Partner',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
