# Generated by Django 3.0.14 on 2022-06-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_personalinfo_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='City',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
