# Generated by Django 3.0.14 on 2022-06-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_personalinfo_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Directorate',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
