# Generated by Django 3.0.14 on 2022-06-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_personalinfo_directorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Ministryy',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
