# Generated by Django 3.0.14 on 2022-06-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_personalinfo_ministryy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='Apartment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Atonomous',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='City',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Directorate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Disability',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Family',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Frname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Ministry',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Ministryy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Mothername',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Partner',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Teleph',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Telephone',
            field=models.CharField(max_length=12),
        ),
    ]
