# Generated by Django 3.0.14 on 2022-06-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_personalinfo_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='checkbox',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
