# Generated by Django 3.0.14 on 2022-06-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_auto_20220627_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='checkbox',
            new_name='checkbox1',
        ),
    ]
