# Generated by Django 3.0.14 on 2022-06-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_auto_20220627_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='checkbox1',
            new_name='Checkbox1',
        ),
    ]
