# Generated by Django 3.0.14 on 2022-06-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_auto_20220627_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='Checkbox1',
            field=models.CharField(max_length=10),
        ),
    ]
