# Generated by Django 3.0.14 on 2022-06-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_auto_20220627_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Checkbox2',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
