# Generated by Django 3.0.14 on 2022-06-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_personalinfo_checkbox2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='Checkbox2',
            field=models.CharField(max_length=10),
        ),
    ]
