# Generated by Django 3.0.14 on 2022-06-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_auto_20220627_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Radio1',
            field=models.CharField(default=50, max_length=50),
        ),
    ]
