# Generated by Django 3.0.14 on 2022-06-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_personalinfo_radio2'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Radio3',
            field=models.CharField(default=50, max_length=50),
        ),
    ]
