# Generated by Django 3.0.14 on 2022-06-28 08:45

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_personalinfo_date1'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Date2',
            field=models.DateField(default=sqlalchemy.sql.expression.false),
        ),
    ]
