# Generated by Django 3.0.14 on 2022-06-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_personalinfo_date2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='File1',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
