# Generated by Django 3.0.14 on 2022-06-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_auto_20220628_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
