# Generated by Django 3.0.14 on 2022-06-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='File2',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='File3',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Fille',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
