# Generated by Django 4.0.5 on 2022-06-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_remove_personalinfo_apartment_alter_personalinfo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='Apartment',
            field=models.CharField(default=50, max_length=50),
        ),
    ]
