# Generated by Django 3.0.14 on 2022-06-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_auto_20220630_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='Fille',
        ),
    ]
