# Generated by Django 3.0.14 on 2022-07-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_user11'),
    ]

    operations = [
        migrations.CreateModel(
            name='User12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
