# Generated by Django 3.0.14 on 2022-07-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_user12'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
