# Generated by Django 4.0.4 on 2022-07-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_auto_20220701_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='File1',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='File2',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='File3',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='File4',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='file1',
            field=models.FileField(default=1, max_length=250, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='file2',
            field=models.FileField(default=1, max_length=250, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='file3',
            field=models.FileField(default=1, max_length=250, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='file4',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user1',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user10',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user11',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user12',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user5',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user6',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user7',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user8',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user9',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
